# Übungsblatt 1: Stabendkräfte und Elementsteifigkeitsmatrix

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np

## Aufgabe 2

In [2]:
EA = 42000
x1 = np.array([1,0])
x2 = np.array([4,4])
l0 = 5

u1 = np.array([0.1, 0.05])
u2 = np.array([0.14,0.09])
v1 = np.array([-1, 0])
v2 = np.array([1, -4])

### 2.1 Stabendkräfte exakt

Verschiebung $u$

In [3]:
l = np.linalg.norm(x1 + u1 - (x2 + u2))
N = EA * (l - l0) / l0
d = (x1 + u1 - (x2 + u2)) / l
t = np.concatenate((-d, d))
P = N * t

print("N = ", N)
print("P = ", P)

N =  470.45316452368405
P =  [ 282.86705496  375.9154283  -282.86705496 -375.9154283 ]


Verschiebung $v$

In [4]:
l = np.linalg.norm(x1 + v1 - (x2 + v2))
N = EA * (l - l0) / l0
d = (x1 + u1 - (x2 + u2)) / l
t = np.concatenate((-d, d))
P = N * t

print("N = ", N)
print("P = ", P)

N =  0.0
P =  [ 0.  0. -0. -0.]


### 2.2 Elementsteifigkeitsmatrix

In [5]:
t0 = np.array([-0.6, -0.8, 0.6, 0.8])
K = EA / l0 * np.outer(t0, t0)

print("K = ", K)

K =  [[ 3024.  4032. -3024. -4032.]
 [ 4032.  5376. -4032. -5376.]
 [-3024. -4032.  3024.  4032.]
 [-4032. -5376.  4032.  5376.]]


### 2.3 Stabendkräfte linearisiert

In [6]:
u = np.concatenate((u1,u2))
v = np.concatenate((v1,v2))

print("Pu = ", K @ u)
print("Pv = ", K @ v)

Pu =  [-282.24 -376.32  282.24  376.32]
Pv =  [ 10080.  13440. -10080. -13440.]


## Aufgabe 4 

In [7]:
from truss import *

Test for $u$

In [8]:
P = truss_p(EA, x1, x2, u1, u2)
K = truss_ke(EA, x1, x2)
NL = truss_n(EA, x1, x2, u1, u2)
PL = truss_p_lin(EA, x1, x2, u1, u2)

print("P = ", P, " (exakt)")
print("K =\n", K)
print("N = ", NL, " (linearisiert)")
print("P = ", PL, " (linearisiert)")

P =  [-282.86705496 -375.9154283   282.86705496  375.9154283 ]  (exakt)
K =
 [[ 3024.  4032. -3024. -4032.]
 [ 4032.  5376. -4032. -5376.]
 [-3024. -4032.  3024.  4032.]
 [-4032. -5376.  4032.  5376.]]
N =  470.40000000000003  (linearisiert)
P =  [-282.24 -376.32  282.24  376.32]  (linearisiert)


Test for $v$

In [9]:
P = truss_p(EA, x1, x2, v1, v2)
PL = truss_p_lin(EA, x1, x2, v1, v2)

print("P = ", P, " (exakt)")
print("P = ", PL, " (linearisiert)")

P =  [-0. -0.  0.  0.]  (exakt)
P =  [ 10080.  13440. -10080. -13440.]  (linearisiert)
